--
-- PostgreSQL
--

CREATE TABLE public.weather (
                                temp_c integer NOT NULL,
                                wind_speed_mph numeric(3,1) NOT NULL,
                                pressure_mb integer NOT NULL,
                                humidity integer NOT NULL,
                                condition character varying(50) NOT NULL,
                                location character varying(100) NOT NULL,
                                create_date timestamp without time zone NOT NULL,
                                id integer NOT NULL
);

ALTER TABLE public.weather OWNER TO postgres;

ALTER TABLE public.weather ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.weather_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );

ALTER TABLE ONLY public.weather
    ADD CONSTRAINT create_date UNIQUE (create_date);

ALTER TABLE ONLY public.weather
    ADD CONSTRAINT id PRIMARY KEY (id);
